env:
  global:
    - CC_TEST_REPORTER_ID=35df1326b07d92df8e12c762fe01e06e12adb06fe3fb8124379372b62380791d

language: ruby
rvm: 2.4

services:
  - postgresql

before_script:
  - psql -c "create role root login password '123456' superuser;" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec spring rake db:create db:migrate db:schema:load db:test:prepare db:test:load
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
